name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Install Deps
        run: npx pnpm i
      - name: Run build
        run: npx pnpm build
