name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: node
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Install Deps
        run: npx pnpm i
      - name: Run tests
        run: npx pnpm test
