name: Update database types

on:
  schedule:
    # daily
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{secrets.SUPABASE_URL}}
      SUPABASE_ANON_KEY: ${{secrets.SUPABASE_ANON_KEY}}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: node
      - run: npx openapi-typescript ${{ secrets.SUPABASE_URL }}/rest/v1/\?apikey\=${{ secrets.SUPABASE_ANON_KEY }} --output types/supabase.ts
      - name: check for file changes
        id: git_status
        run: |
          echo "::set-output name=status::$(git status -s)"
      - name: Save
        uses: mikeal/publish-to-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: 'main'
